name: build-sphinx-to-gh-pages
env:
  GITHUB_ACTOR: annegentle
  GITHUB_REPOSITORY: annegentle/create-demo
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
on: 
  push:
    branches: [ main ]
jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script for Sphinx pages
        run: "docs/buildsite.sh"
        shell: bash
