name: build-sphinx-to-gh-pages
env:
  GITHUB_ACTOR: annegentle
  GITHUB_REPOSITORY: annegentle/create-demo
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
on: 
  push:
    branches: [ main ]
jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get prerequisites
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          apt-get update
          apt-get install -y git
          git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash
      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: "docs/buildsite.sh"
        shell: bash

