name: build-sphinx-to-gh-pages
env:
  GITHUB_ACTOR: annegentle
  GITHUB_REPOSITORY: annegentle/create-demo
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
  GITHUB_ACTION_PATH: ./scripts
on: 
  push:
    branches: [ main ]
jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: $GITHUB_ACTION_PATH/buildsite.sh
        shell: bash

